// Generated from migrations/*.sql by scripts/schema.mjs. Runs once per worker instance.
// SCHEMA statements are idempotent; ALTERS run one by one and "duplicate column" errors are ignored.
export const SCHEMA: string[] = [
 "CREATE TABLE IF NOT EXISTS settings ( key TEXT PRIMARY KEY, value TEXT NOT NULL )",
 "CREATE TABLE IF NOT EXISTS sites ( id TEXT PRIMARY KEY, name TEXT NOT NULL, subdomain TEXT NOT NULL UNIQUE, accent TEXT NOT NULL DEFAULT 'brass', theme TEXT NOT NULL DEFAULT 'auto', status TEXT NOT NULL DEFAULT 'building', tagline TEXT NOT NULL DEFAULT '', created_at INTEGER NOT NULL )",
 "CREATE TABLE IF NOT EXISTS pages ( id TEXT PRIMARY KEY, site_id TEXT NOT NULL REFERENCES sites(id) ON DELETE CASCADE, slug TEXT NOT NULL, title TEXT NOT NULL, template TEXT NOT NULL, content TEXT NOT NULL DEFAULT '{}', published INTEGER NOT NULL DEFAULT 0, views INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, UNIQUE (site_id, slug) )",
 "CREATE TABLE IF NOT EXISTS lists ( id TEXT PRIMARY KEY, name TEXT NOT NULL, site_id TEXT REFERENCES sites(id) ON DELETE SET NULL, welcome_enabled INTEGER NOT NULL DEFAULT 0, welcome_subject TEXT NOT NULL DEFAULT '', welcome_body TEXT NOT NULL DEFAULT '', created_at INTEGER NOT NULL )",
 "CREATE TABLE IF NOT EXISTS contacts ( id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE COLLATE NOCASE, name TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'subscribed', source TEXT NOT NULL DEFAULT '', consent_at INTEGER, consent_text TEXT NOT NULL DEFAULT '', token TEXT NOT NULL UNIQUE, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL )",
 "CREATE TABLE IF NOT EXISTS list_members ( list_id TEXT NOT NULL REFERENCES lists(id) ON DELETE CASCADE, contact_id TEXT NOT NULL REFERENCES contacts(id) ON DELETE CASCADE, added_at INTEGER NOT NULL, PRIMARY KEY (list_id, contact_id) )",
 "CREATE TABLE IF NOT EXISTS campaigns ( id TEXT PRIMARY KEY, name TEXT NOT NULL, subject TEXT NOT NULL DEFAULT '', preheader TEXT NOT NULL DEFAULT '', body TEXT NOT NULL DEFAULT '', list_id TEXT REFERENCES lists(id) ON DELETE SET NULL, site_id TEXT REFERENCES sites(id) ON DELETE SET NULL, status TEXT NOT NULL DEFAULT 'draft', scheduled_at INTEGER, sent_at INTEGER, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL )",
 "CREATE TABLE IF NOT EXISTS sends ( id TEXT PRIMARY KEY, campaign_id TEXT REFERENCES campaigns(id) ON DELETE CASCADE, list_id TEXT, kind TEXT NOT NULL, contact_id TEXT REFERENCES contacts(id) ON DELETE CASCADE, email TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'queued', error TEXT, provider_id TEXT, opened_at INTEGER, clicked_at INTEGER, created_at INTEGER NOT NULL, sent_at INTEGER )",
 "CREATE INDEX IF NOT EXISTS idx_pages_site ON pages(site_id)",
 "CREATE INDEX IF NOT EXISTS idx_members_c ON list_members(contact_id)",
 "CREATE INDEX IF NOT EXISTS idx_sends_queue ON sends(status, created_at)",
 "CREATE INDEX IF NOT EXISTS idx_sends_campaign ON sends(campaign_id)",
 "CREATE INDEX IF NOT EXISTS idx_contacts_time ON contacts(created_at)",
 "CREATE TABLE IF NOT EXISTS login_tokens ( hash TEXT PRIMARY KEY, email TEXT NOT NULL, expires_at INTEGER NOT NULL, used_at INTEGER, created_at INTEGER NOT NULL )",
 "CREATE TABLE IF NOT EXISTS sessions ( hash TEXT PRIMARY KEY, email TEXT NOT NULL, expires_at INTEGER NOT NULL, created_at INTEGER NOT NULL, user_agent TEXT NOT NULL DEFAULT '' )",
 "CREATE INDEX IF NOT EXISTS idx_login_email ON login_tokens(email, created_at)",
 "CREATE TABLE IF NOT EXISTS sequences ( id TEXT PRIMARY KEY, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'draft', trigger TEXT NOT NULL DEFAULT 'list', trigger_list_id TEXT, trigger_campaign_id TEXT, site_id TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL )",
 "CREATE TABLE IF NOT EXISTS sequence_steps ( id TEXT PRIMARY KEY, sequence_id TEXT NOT NULL, position INTEGER NOT NULL, delay_minutes INTEGER NOT NULL DEFAULT 0, condition TEXT NOT NULL DEFAULT 'always', subject TEXT NOT NULL DEFAULT '', preheader TEXT NOT NULL DEFAULT '', body TEXT NOT NULL DEFAULT '', created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL )",
 "CREATE TABLE IF NOT EXISTS enrollments ( id TEXT PRIMARY KEY, sequence_id TEXT NOT NULL, contact_id TEXT NOT NULL, step_index INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'active', exit_reason TEXT, next_at INTEGER, last_send_id TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, UNIQUE (sequence_id, contact_id) )",
 "CREATE TABLE IF NOT EXISTS email_events ( id TEXT PRIMARY KEY, type TEXT NOT NULL, provider_id TEXT, email TEXT, detail TEXT NOT NULL DEFAULT '', created_at INTEGER NOT NULL )",
 "CREATE INDEX IF NOT EXISTS idx_steps_seq ON sequence_steps(sequence_id, position)",
 "CREATE INDEX IF NOT EXISTS idx_enroll_due ON enrollments(status, next_at)",
 "CREATE INDEX IF NOT EXISTS idx_enroll_seq ON enrollments(sequence_id, status)",
 "CREATE INDEX IF NOT EXISTS idx_enroll_c ON enrollments(contact_id)",
 "CREATE INDEX IF NOT EXISTS idx_sends_provider ON sends(provider_id)",
 "CREATE INDEX IF NOT EXISTS idx_events_time ON email_events(created_at)",
 "CREATE TABLE IF NOT EXISTS social_posts ( id TEXT PRIMARY KEY, profile_id TEXT NOT NULL, content TEXT NOT NULL DEFAULT '', media TEXT NOT NULL DEFAULT '[]', targets TEXT NOT NULL DEFAULT '[]', options TEXT NOT NULL DEFAULT '{}', status TEXT NOT NULL DEFAULT 'draft', scheduled_at INTEGER, published_at INTEGER, zernio_id TEXT, results TEXT NOT NULL DEFAULT '[]', error TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL )",
 "CREATE INDEX IF NOT EXISTS idx_social_profile ON social_posts(profile_id, status)",
 "CREATE INDEX IF NOT EXISTS idx_social_due ON social_posts(status, scheduled_at)",
 "CREATE TABLE IF NOT EXISTS files ( id TEXT PRIMARY KEY, key TEXT NOT NULL UNIQUE, name TEXT NOT NULL, folder TEXT NOT NULL DEFAULT '', type TEXT NOT NULL, kind TEXT NOT NULL, size INTEGER NOT NULL DEFAULT 0, width INTEGER, height INTEGER, alt TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'ready', upload_id TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL )",
 "CREATE INDEX IF NOT EXISTS idx_files_folder ON files(folder, created_at)",
 "CREATE INDEX IF NOT EXISTS idx_files_time ON files(created_at)",
 "CREATE TABLE IF NOT EXISTS links ( id TEXT PRIMARY KEY, code TEXT NOT NULL UNIQUE, url TEXT NOT NULL, source_type TEXT NOT NULL DEFAULT 'manual', source_id TEXT, platform TEXT, profile_id TEXT, original TEXT NOT NULL DEFAULT '', clicks INTEGER NOT NULL DEFAULT 0, last_click_at INTEGER, created_at INTEGER NOT NULL )",
 "CREATE INDEX IF NOT EXISTS idx_links_source ON links(source_type, source_id)",
 "CREATE TABLE IF NOT EXISTS link_days ( link_id TEXT NOT NULL, day TEXT NOT NULL, clicks INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (link_id, day) )",
 "CREATE TABLE IF NOT EXISTS upload_links ( hash TEXT PRIMARY KEY, id TEXT NOT NULL UNIQUE, folder TEXT NOT NULL DEFAULT '', note TEXT NOT NULL DEFAULT '', max_files INTEGER NOT NULL DEFAULT 10, expires_at INTEGER NOT NULL, created_at INTEGER NOT NULL )",
 "CREATE TABLE IF NOT EXISTS contact_fields ( id TEXT PRIMARY KEY, key TEXT NOT NULL UNIQUE, label TEXT NOT NULL, type TEXT NOT NULL DEFAULT 'text', options TEXT NOT NULL DEFAULT '[]', created_at INTEGER NOT NULL )",
 "CREATE TABLE IF NOT EXISTS forms ( id TEXT PRIMARY KEY, name TEXT NOT NULL, site_id TEXT, list_id TEXT, fields TEXT NOT NULL DEFAULT '[]', button TEXT NOT NULL DEFAULT 'Sign up', success TEXT NOT NULL DEFAULT 'Thanks, you’re on the list.', redirect_url TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'active', created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL )",
 "CREATE TABLE IF NOT EXISTS form_submissions ( id TEXT PRIMARY KEY, form_id TEXT NOT NULL, contact_id TEXT, data TEXT NOT NULL DEFAULT '{}', page_url TEXT NOT NULL DEFAULT '', ip_hash TEXT NOT NULL DEFAULT '', created_at INTEGER NOT NULL )",
 "CREATE INDEX IF NOT EXISTS idx_subs_form ON form_submissions(form_id, created_at)",
 "CREATE INDEX IF NOT EXISTS idx_subs_contact ON form_submissions(contact_id)",
 "CREATE INDEX IF NOT EXISTS idx_subs_ip ON form_submissions(ip_hash, created_at)",
 "CREATE TABLE IF NOT EXISTS segments ( id TEXT PRIMARY KEY, name TEXT NOT NULL, rules TEXT NOT NULL DEFAULT '{\"match\":\"all\",\"rules\":[]}', created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL )",
 "CREATE TABLE IF NOT EXISTS brand_briefs ( profile_id TEXT PRIMARY KEY, workspace TEXT NOT NULL DEFAULT 'main', voice TEXT NOT NULL DEFAULT '', audience TEXT NOT NULL DEFAULT '', pillars TEXT NOT NULL DEFAULT '[]', dos TEXT NOT NULL DEFAULT '', donts TEXT NOT NULL DEFAULT '', hashtags TEXT NOT NULL DEFAULT '', links TEXT NOT NULL DEFAULT '[]', examples TEXT NOT NULL DEFAULT '', cadence TEXT NOT NULL DEFAULT '{}', pinterest_board TEXT NOT NULL DEFAULT '', producer_on INTEGER NOT NULL DEFAULT 0, updated_at INTEGER NOT NULL )",
 "CREATE TABLE IF NOT EXISTS draft_batches ( id TEXT PRIMARY KEY, workspace TEXT NOT NULL DEFAULT 'main', profile_id TEXT NOT NULL, title TEXT NOT NULL, summary TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'open', created_at INTEGER NOT NULL, ready_at INTEGER )",
 "CREATE INDEX IF NOT EXISTS idx_batches_status ON draft_batches(status, created_at)",
 "CREATE TABLE IF NOT EXISTS initiatives ( id TEXT PRIMARY KEY, workspace TEXT NOT NULL DEFAULT 'main', name TEXT NOT NULL, tag TEXT NOT NULL DEFAULT '', goal TEXT NOT NULL DEFAULT '', target INTEGER, starts_at INTEGER, ends_at INTEGER, notes TEXT NOT NULL DEFAULT '', archived INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL )",
 "CREATE TABLE IF NOT EXISTS social_brands ( id TEXT PRIMARY KEY, name TEXT NOT NULL, created_at INTEGER NOT NULL )",
 "CREATE TABLE IF NOT EXISTS social_apps ( platform TEXT PRIMARY KEY, client_id TEXT NOT NULL, secret TEXT NOT NULL, options TEXT NOT NULL DEFAULT '{}', updated_at INTEGER NOT NULL )",
 "CREATE TABLE IF NOT EXISTS social_accounts ( id TEXT PRIMARY KEY, profile_id TEXT NOT NULL, platform TEXT NOT NULL, external_id TEXT NOT NULL, username TEXT NOT NULL DEFAULT '', display_name TEXT NOT NULL DEFAULT '', picture TEXT NOT NULL DEFAULT '', token TEXT NOT NULL, refresh_token TEXT, secret TEXT, expires_at INTEGER, refresh_expires_at INTEGER, token_issued_at INTEGER NOT NULL, meta TEXT NOT NULL DEFAULT '{}', status TEXT NOT NULL DEFAULT 'ok', status_note TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL )",
 "CREATE UNIQUE INDEX IF NOT EXISTS idx_social_accounts_brand ON social_accounts(profile_id, platform)",
 "CREATE TABLE IF NOT EXISTS social_oauth ( state TEXT PRIMARY KEY, platform TEXT NOT NULL, profile_id TEXT NOT NULL, verifier TEXT NOT NULL, created_at INTEGER NOT NULL )",
 "CREATE TABLE IF NOT EXISTS social_deliveries ( id TEXT PRIMARY KEY, post_id TEXT NOT NULL, account_id TEXT NOT NULL, platform TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'queued', step TEXT NOT NULL DEFAULT 'start', data TEXT NOT NULL DEFAULT '{}', attempts INTEGER NOT NULL DEFAULT 0, next_at INTEGER NOT NULL, locked_until INTEGER NOT NULL DEFAULT 0, external_id TEXT, url TEXT, error TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL )",
 "CREATE INDEX IF NOT EXISTS idx_deliveries_due ON social_deliveries(status, next_at)",
 "CREATE INDEX IF NOT EXISTS idx_deliveries_post ON social_deliveries(post_id)",
];
export const ALTERS: string[] = [
 "ALTER TABLE sends ADD COLUMN step_id TEXT",
 "ALTER TABLE sends ADD COLUMN enrollment_id TEXT",
 "ALTER TABLE sends ADD COLUMN delivered_at INTEGER",
 "ALTER TABLE sends ADD COLUMN bounced_at INTEGER",
 "ALTER TABLE sends ADD COLUMN complained_at INTEGER",
 "CREATE INDEX IF NOT EXISTS idx_sends_step ON sends(step_id)",
 "ALTER TABLE contacts ADD COLUMN ref_link TEXT",
 "CREATE INDEX IF NOT EXISTS idx_contacts_ref ON contacts(ref_link)",
 "ALTER TABLE social_posts ADD COLUMN metrics TEXT",
 "ALTER TABLE social_posts ADD COLUMN metrics_at INTEGER",
 "ALTER TABLE files ADD COLUMN upload_link TEXT",
 "CREATE INDEX IF NOT EXISTS idx_files_link ON files(upload_link)",
 "ALTER TABLE contacts ADD COLUMN props TEXT",
 "ALTER TABLE campaigns ADD COLUMN segment_id TEXT",
 "ALTER TABLE social_posts ADD COLUMN batch_id TEXT",
 "ALTER TABLE social_posts ADD COLUMN planned_at INTEGER",
 "ALTER TABLE social_posts ADD COLUMN origin TEXT",
 "ALTER TABLE social_posts ADD COLUMN note TEXT",
 "CREATE INDEX IF NOT EXISTS idx_social_batch ON social_posts(batch_id)",
 "ALTER TABLE campaigns ADD COLUMN initiative_id TEXT",
 "ALTER TABLE social_posts ADD COLUMN initiative_id TEXT",
 "ALTER TABLE forms ADD COLUMN initiative_id TEXT",
 "ALTER TABLE pages ADD COLUMN initiative_id TEXT",
 "CREATE INDEX IF NOT EXISTS idx_campaigns_init ON campaigns(initiative_id)",
 "CREATE INDEX IF NOT EXISTS idx_social_init ON social_posts(initiative_id)",
 "ALTER TABLE social_posts ADD COLUMN zernio_status TEXT",
 "ALTER TABLE social_posts ADD COLUMN zernio_results TEXT",
 "ALTER TABLE pages ADD COLUMN previous TEXT",
];
